export const APPEND_DIGIT = "APPEND_DIGIT";
export const APPEND_DECIMAL = "APPEND_DECIMAL";
export const DELETE_DIGIT = "DELETE_DIGIT";
export const ERASE_RESULT = "ERASE_RESULT";
export const DELETE_CACHE = "DELETE_CACHE";
export const CACHE_RESULT = "CACHE_RESULT";
export const LOAD_CACHE = "LOAD_CACHE";
export const QUEUE_OPERATION = "QUEUE_OPERATION";
